import { useEffect, useState } from 'react';
import { archiveTodayTask, getTodayTasks, updateTodayTaskStatus, type TodayTask, type TodayTaskStatus } from '../api/todayTasks';

export function TodayTasksPage() {
  const [tasks, setTasks] = useState<TodayTask[]>([]); const [statuses, setStatuses] = useState<TodayTaskStatus[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState<string | null>(null); const [menu, setMenu] = useState<string | null>(null); const [archiveId, setArchiveId] = useState<string | null>(null);
  const load = async () => { setError(''); try { const result = await getTodayTasks(); setTasks(result.tasks); setStatuses(result.statuses); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load tasks.'); } };
  useEffect(() => { void load(); }, []);
  async function changeStatus(task: TodayTask, status: string) { setBusy(task.id); setMenu(null); try { await updateTodayTaskStatus(task.id, status); setTasks(items => items.map(item => item.id === task.id ? { ...item, status } : item)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update task.'); } finally { setBusy(null); } }
  async function archive() { if (!archiveId) return; setBusy(archiveId); try { await archiveTodayTask(archiveId); setTasks(items => items.filter(item => item.id !== archiveId)); setArchiveId(null); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to archive task.'); } finally { setBusy(null); } }
  return <><header className="page-header"><span className="app-mark" aria-hidden="true">✓</span><div><h1>Today's tasks</h1><p>A quick view of what is planned for today.</p></div></header><section className="today-list"><div className="section-heading"><h2>Tasks <span className="count">{tasks.length}</span></h2><button className="text-button" onClick={() => void load()}>Refresh</button></div>{error && <p className="error">{error}</p>}{tasks.length === 0 && !error ? <div className="empty-state"><span>✓</span><h3>Nothing planned</h3><p>Your Notion today view is empty.</p></div> : <ul>{tasks.map(task => <li className="today-item" key={task.id}><div className="today-details"><strong>{task.name}</strong><small>{task.projects.length ? task.projects.join(', ') : 'No project'}</small></div><div className="today-actions"><div className="status-menu"><button className="status-button" disabled={busy === task.id} onClick={() => setMenu(menu === task.id ? null : task.id)}>{busy === task.id ? 'Saving…' : task.status}</button>{menu === task.id && <div className="status-options">{statuses.map(status => <button key={status.name} onClick={() => void changeStatus(task, status.name)}>{status.name}</button>)}</div>}</div><button className="delete-button" aria-label={`Archive ${task.name}`} disabled={busy === task.id} onClick={() => setArchiveId(task.id)}>Archive</button></div></li>)}</ul>}</section>{archiveId && <div className="confirm-backdrop" role="presentation"><section className="confirm-dialog" role="dialog" aria-modal="true" aria-label="Confirm archive"><h2>Archive task?</h2><p>The task will be moved to the Notion trash.</p><div><button className="delete-button" onClick={() => void archive()}>Archive</button><button className="text-button" onClick={() => setArchiveId(null)}>Cancel</button></div></section></div>}</>;
}
