using System.Text.Json.Serialization;
using NotionManagementFunctionApp.SendNotionTaskNotifications;
namespace NotionManagementFunctionApp.TaskXp;
public sealed record TaskXpInput(NotionTaskSnapshot Task, string Source, string SourceEventId, DateTimeOffset OccurredAt);
public sealed class TaskStateDocument { [JsonPropertyName("id")] public string Id { get; init; } = ""; public string ProfileId { get; init; } = TaskXpRepository.ProfileId; public string Type { get; init; } = "task-state"; public string TaskId { get; init; } = ""; public bool IsCompleted { get; init; } public DateTimeOffset LatestOccurredAt { get; init; } public int CompletionCycle { get; init; } public int? ActiveAwardXp { get; init; } [JsonPropertyName("_etag")] public string? ETag { get; init; } }
public sealed class XpTotalDocument { [JsonPropertyName("id")] public string Id { get; init; } = "xp-total"; public string ProfileId { get; init; } = TaskXpRepository.ProfileId; public string Type { get; init; } = "xp-total"; public int TotalXp { get; init; } [JsonPropertyName("_etag")] public string? ETag { get; init; } }
public sealed class XpEventDocument { [JsonPropertyName("id")] public string Id { get; init; } = ""; public string ProfileId { get; init; } = TaskXpRepository.ProfileId; public string Type { get; init; } = "xp-event"; public string TaskId { get; init; } = ""; public string TaskName { get; init; } = ""; public string ChangeType { get; init; } = ""; public int XpAmount { get; init; } public string? ObservedEffort { get; init; } public string Effort { get; init; } = ""; public string Source { get; init; } = ""; public DateTimeOffset OccurredAt { get; init; } public DateTimeOffset RecordedAt { get; init; } }
public sealed class DeliveryReceiptDocument { [JsonPropertyName("id")] public string Id { get; init; } = ""; public string ProfileId { get; init; } = TaskXpRepository.ProfileId; public string Type { get; init; } = "delivery-receipt"; public string Source { get; init; } = ""; public string SourceEventId { get; init; } = ""; public string TaskId { get; init; } = ""; public DateTimeOffset OccurredAt { get; init; } public DateTimeOffset ReceivedAt { get; init; } }
public sealed record XpHistoryItem(string TaskName, string ChangeType, int XpAmount, string Effort, DateTimeOffset OccurredAt, string Source);
public sealed record XpHistoryPage(IReadOnlyList<XpHistoryItem> Events, string? ContinuationToken);
